### PR TITLE
Hindu/Indian Time Dataset

### PR DESCRIPTION
**Pull request by pushuzhang**
Please review this, should be good to go :)

### CODE REVIEW

**Comment by JEF1056** [comment]
Merging the most recent changes into your branch;
A few things that need fixing:
- Please update dataset.json
- The column headings are being processed as part of the dataset; Please fix that in the script

**Review by JEF1056 — CHANGES_REQUESTED** [review]
Merging the most recent changes into your branch;
A few things that need fixing:
- The column headings are being processed as part of the dataset; Please fix that in the script
- Upload the dataset to google cloud
- Please update dataset.json

**Comment by pushuzhang** [comment]
Thank you for reviewing!

> * Upload the dataset to google cloud
Do you mean our shared google drive?

**Comment by pushuzhang** [comment]
Thanks a lot for reviewing, I have uploaded my dataset to google cloud.

**Pull request merged**
